AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'config.rb'
    - 'octopodes.gemspec'
    - 'spec/**/*'

Lint/HandleExceptions:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 68

Metrics/ClassLength:
  Max: 112

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 55

Metrics/PerceivedComplexity:
  Max: 15

Style/AlignArray:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: true

Style/EmptyLines:
  Enabled: true

Style/EmptyLinesAroundAccessModifier:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  Enabled: true

Style/EmptyLinesAroundClassBody:
  Enabled: true

Style/EmptyLinesAroundMethodBody:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/IndentationWidth:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/Next:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RegexpLiteral:
  MaxSlashes: 0

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAfterControlKeyword:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceBeforeBlockBraces:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/VariableName:
  Enabled: true

Style/WordArray:
  MinSize: 4
